openapi: 3.0.3

info:
  title: Spring Boot REST API Server
  version: '1.0.0'
  description: An example REST API server using Spring Boot.

servers:
  - url: 'http://localhost:8080'

tags:
  - name: user
  - name: post

paths:

  /user/all:
    description: Get all users.
    get:
      responses:
        '200':
          description: List of users.
      tags:
        - user

  /user/add:
    description: Add user.
    post:
      requestBody:
        content:
          application/json:
            example:
              name: rulyox
              age: 20
        required: true
      responses:
        '200':
          description: Added user id.
      tags:
        - user

  /user/id:
    description: Get user by id.
    get:
      parameters:
        - name: id
          in: query
          schema:
            type: number
          example: '1'
          required: true
          allowEmptyValue: false
      responses:
        '200':
          description: Corresponding user.
      tags:
        - user

  /user/count:
    description: Get user count.
    get:
      responses:
        '200':
          description: Number of users.
          content:
            application/json:
              example:
                count: '3'
      tags:
        - user

  /post/all:
    description: Get all post.
    get:
      responses:
        '200':
          description: List of posts.
      tags:
        - post

  /post/add:
    description: Add post.
    post:
      requestBody:
        content:
          application/json:
            example:
              name: rulyox
              age: 20
        required: true
      responses:
        '200':
          description: Added post id.
      tags:
        - post

  /post/id:
    description: Get post by id.
    get:
      parameters:
        - name: id
          in: query
          schema:
            type: number
          example: '1'
          required: true
          allowEmptyValue: false
      responses:
        '200':
          description: Corresponding post.
      tags:
        - post

  /post/count:
    description: Get post count.
    get:
      responses:
        '200':
          description: Number of posts.
          content:
            application/json:
              example:
                count: '3'
      tags:
        - post
